services:
  deptrac:
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=deptrac
      - COMPOSER_CACHE_DIR=/home/deptrac/.composer
    volumes:
      - ./:/var/www/deptrac
      - user-data:/home/deptrac/
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host-gateway}

volumes:
  user-data:
